# Generated by Django 3.0 on 2020-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='eagleID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
