# Generated by Django 3.0 on 2020-04-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200415_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='option_five',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_four',
            field=models.CharField(max_length=30),
        ),
    ]
