# Generated by Django 3.0 on 2020-04-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_peer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('comment_one', models.TextField()),
            ],
        ),
    ]
